### ISSUE TITLE
Uh, is this why this didn't work?

### ISSUE THREAD

**Issue by tlunter** [k-langer/EECE4534_Zhone#1]
https://github.com/k-langer/EECE4534_Zhone/blob/master/src/main.c#L62

Shouldn't this have been `SSM2602_TX | SSM2602_RX` since we're like trying to receive as well?

WHAT IF IT WORKED ALL ALONG AND WE JUST FORGOT THAT.

**Comment by k-langer** [comment]
Oh man! We need to get the gang back together, hit up Gunar for a couple of PALs, and fire up some VMs. That is certainly an error, but it is the only one? Did you talk to Mark's group, did they find it or did you? Why are you even looking at this code?

**Comment by javi7** [comment]
me & gunar are tight. capstone buddies :)

**Comment by markhatch** [comment]
We will be testing this weekend and we can let you all know :D

**Comment by k-langer** [comment]
@markhatch 
Thanks Mark, we need to know! 

@javi7 
ready for capstone?

**Comment by JuanAntelo** [comment]
Que..You guys are either delusional from pulling multiple all-nighters for
capstone or are hammered on a Wednesday night.  SSM2602_RX is never going
to be passed into init since SSM2602_TX is always going to be true
/joke..but not really lol

But ya I'm sure it's along those lines, I actually wouldn't mind taking a
look at the init function - anyone got that file laying around? Its not in
the repo.

On a side note - The real reason why our project failed was obviously due
to gunar's doctrine of imposing the waterfall methodology onto us as well
as a lack of comprehensive unit tests, code reviews, and code coverage
analysis.

And eclipse.

/sarcasm(Except for the eclipse part)

**Comment by k-langer** [comment]
@JuanAntelo 
FYI it's a bitwise or,  SSM2602_RX and SSM2602_TX mask to different bit pattern so the | of the two of them is a lovely marriage. 

You should be able to find the init function on the nuforge website if you go digging.

**Comment by JuanAntelo** [comment]
Ya ik..obv wouldnt work but I see the joke made now lol. & nah aint nobody
got time for that

**Comment by markhatch** [comment]
Do you guys remember which binary file you loaded onto the FPGA? We are
getting a different CRC...
In the FPGA folder of the repo there are the following binaries:
fpga_gpio_uart
fpga_gpio_uart_connected
TLL6527m_v1_2_FPGA

We just uncommented the "fpga_gpio_uart.h" in maine and used
fpga_programmer() to write it in, but it doesn't seem to be working with a
simple wire loopback for the uartTx and uartRx.
I'm sure it's been a while since you guys worked on this project, but I
figured it was worth a shot.

https://github.com/k-langer/EECE4534_Zhone/blob/master/src/main.c#L50

**Comment by tlunter** [comment]
I can't remember exactly how we loaded it.  I think I used minicom more often than the header method since it seemed to be more reliable.  There is some documentation about how to do this under _Program Secondary FPGA_ on [this](https://nuforge.coe.neu.edu/gf/project/pal/wiki/?pagename=recover) page.

**Comment by javi7** [comment]
thanks for closing. this has been bugging me.

**Comment by tlunter** [comment]
now we'll never know though. could it have been done.

**Comment by k-langer** [comment]
It totally could have been done. Closing resolved
